define('browse_for_folder_button/nls/browse_for_folder_button_en-us',{
'dijit/form/nls/validate':{"invalidMessage":"The value entered is not valid.","missingMessage":"This value is required.","rangeMessage":"This value is out of range.","_localized":{}}
,
'dgrid/extensions/nls/columnHider':{"popupTriggerLabel":"Show or hide columns","popupLabel":"Show or hide columns","_localized":{}}
,
'mw-keybindings/l10n/nls/keyBindings':{"ALT":"Alt","BACKSPACE":"Backspace","CAPS_LOCK":"Caps Lock","CLEAR":"Clear","CTRL":"Ctrl","DELETE":"Delete","DOWN":"Down","ENTER":"Enter","END":"End","ESCAPE":"Escape","HELP":"Help","HOME":"Home","INSERT":"Insert","LEFT":"Left","NUM_LOCK":"Num Lock","NUM_PAD":"Num Pad","PAGE_UP":"Page Up","PAGE_DOWN":"Page Down","PAUSE_BREAK":"Pause","RIGHT":"Right","SCROLL_LOCK":"Scroll Lock","SHIFT":"Shift","SPACE":"Space","TAB":"Tab","UP":"Up","WINDOWS":"Windows","_localized":{}}
,
'mw-filebrowser/l10n/nls/FileBrowserResources':{"name":"Name","size":"Size","dateModified":"Date Modified","type":"Type","publishedMySite":"(my site)","stopGrouping":"Stop Grouping","groupBy":"Group By","dndCopyMessage":"Copy ${0} item(s)","dndMoveMessage":"Move ${0} item(s)","defaultFolderType":"Folder","defaultFileType":"${0} File","kb":"KB","mb":"MB","gb":"GB","tb":"TB","pb":"PB","eb":"EB","zb":"ZB","yb":"YB","fileSize":"${0} ${1}","fileGroup":"File","small":"Small","medium":"Medium","large":"Large","older":"Older","lastWeek":"Last Week","twoWeeksAgo":"Two Weeks Ago","threeWeeksAgo":"Three Weeks Ago","today":"Today","sunday":"Sunday","monday":"Monday","tuesday":"Tuesday","wednesday":"Wednesday","thursday":"Thursday","friday":"Friday","saturday":"Saturday","_localized":{}}
,
'filechooser-ui/l10n/gen/resources/filechooser/nls/filechooser':{"blankFileNameError":"You must specify a file name","cancel":"Cancel","currentFolderIsReadOnly":"The selected folder is not writable","fileMustExist":"The file must exist in the selected folder","fileNameLengthError":"File name can't be longer than 128 characters","fileOrFolderExistsError":"File or folder already exists","invalidFileNameError":"These characters are invalid in a file name: \\ / : * ?  \" < > |","invalidMFileNameError":"MATLAB names must start with a letter and contain only letters, numbers and underscores","mFileNameLengthError":"MATLAB file name should be less than 63 characters","ok":"OK","publishedMySite":"(my site)","saveAsFileDropDownLabel":"Type","saveAsFileNameLabel":"Save as","sharedWithMe":"(with me)","_localized":{}}
});