//>>built
/*
 Copyright 2015 The MathWorks, Inc.
 @exports MW/utils/deprecation
*/
require({cache:{"dojo/require":function(){define(["./_base/loader"],function(g){return{dynamic:0,normalize:function(f){return f},load:g.require}})},"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(g,f){var d=document.createElement("div"),a=d.matches||d.webkitMatchesSelector||d.mozMatchesSelector||d.msMatchesSelector||d.oMatchesSelector,b=d.querySelectorAll,c=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;g.add("dom-matches-selector",!!a);g.add("dom-qsa",!!b);var e=
function(a,c){if(h&&-1<a.indexOf(","))return h(a,c);var d=c?c.ownerDocument||c:f.doc||document,k=(b?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(a);c=c||d;if(k){var u=8===g("ie")&&g("quirks")?c.nodeType===d.nodeType:null!==c.parentNode&&9!==c.nodeType&&c.parentNode===d;if(k[2]&&u){var l=f.byId?f.byId(k[2],d):d.getElementById(k[2]);if(!l||k[1]&&k[1]!=l.tagName.toLowerCase())return[];if(c!=d)for(a=l;a!=c;)if(a=a.parentNode,
!a)return[];return k[3]?e(k[3],l):[l]}if(k[3]&&c.getElementsByClassName)return c.getElementsByClassName(k[4]);if(k[5])if(l=c.getElementsByTagName(k[5]),k[4]||k[6])a=(k[4]||"")+k[6];else return l}if(b)return 1===c.nodeType&&"object"!==c.nodeName.toLowerCase()?q(c,a,c.querySelectorAll):c.querySelectorAll(a);l||(l=c.getElementsByTagName("*"));k=[];d=0;for(u=l.length;d<u;d++){var t=l[d];1==t.nodeType&&r(t,a,c)&&k.push(t)}return k},q=function(b,a,e){var k=b,d=b.getAttribute("id"),f=d||"__dojo__",l=b.parentNode,
h=/^\s*[+~]/.test(a);if(h&&!l)return[];d?f=f.replace(/'/g,"\\$\x26"):b.setAttribute("id",f);h&&l&&(b=b.parentNode);a=a.match(c);for(l=0;l<a.length;l++)a[l]="[id\x3d'"+f+"'] "+a[l];a=a.join(",");try{return e.call(b,a)}finally{d||k.removeAttribute("id")}};if(!g("dom-matches-selector"))var r=function(){function b(b,a,c){var k=a.charAt(0);if('"'==k||"'"==k)a=a.slice(1,-1);a=a.replace(/\\/g,"");var e=h[c||""];return function(c){return(c=c.getAttribute(b))&&e(c,a)}}function a(b){return function(a,c){for(;(a=
a.parentNode)!=c;)if(b(a,c))return!0}}function c(b){return function(a,c){a=a.parentNode;return b?a!=c&&b(a,c):a==c}}function k(a,b){return a?function(c,k){return b(c)&&a(c,k)}:b}var e="div"==d.tagName?"toLowerCase":"toUpperCase",f={"":function(a){a=a[e]();return function(b){return b.tagName==a}},".":function(a){var b=" "+a+" ";return function(c){return-1<c.className.indexOf(a)&&-1<(" "+c.className+" ").indexOf(b)}},"#":function(a){return function(b){return b.id==a}}},h={"^\x3d":function(a,b){return 0==
a.indexOf(b)},"*\x3d":function(a,b){return-1<a.indexOf(b)},"$\x3d":function(a,b){return a.substring(a.length-b.length,a.length)==b},"~\x3d":function(a,b){return-1<(" "+a+" ").indexOf(" "+b+" ")},"|\x3d":function(a,b){return 0==(a+"-").indexOf(b+"-")},"\x3d":function(a,b){return a==b},"":function(a,b){return!0}},g={};return function(e,d,l){var h=g[d];if(!h){if(d.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,function(e,
d,l,u,g,r,q){u?h=k(h,f[l||""](u.replace(/\\/g,""))):d?h=(" "==d?a:c)(h):g&&(h=k(h,b(g,q,r)));return""}))throw Error("Syntax error in query");if(!h)return!0;g[d]=h}return h(e,l)}}();if(!g("dom-qsa"))var h=function(a,b){for(var d=a.match(c),k=[],f=0;f<d.length;f++){a=new String(d[f].replace(/\s*$/,""));a.indexOf=escape;a=e(a,b);for(var h=0,l=a.length;h<l;h++){var g=a[h];k[g.sourceIndex]=g}}b=[];for(f in k)b.push(k[f]);return b};e.match=a?function(b,c,e){return e&&9!=e.nodeType?q(e,c,function(c){return a.call(b,
c)}):a.call(b,c)}:r;return e})},"xstyle/core/load-css":function(){define([],function(){function g(c){if(a.createStyleSheet){var e=a.createStyleSheet();e.cssText=c;return e.owningElement}e=a.createElement("style");e.setAttribute("type","text/css");e.appendChild(a.createTextNode(c));b.insertBefore(e,b.firstChild);return e}function f(c,e,f){var r=d[c];if(r)return h=g(r),e(h);var h=a.createElement("link");h.type="text/css";h.rel="stylesheet";h.href=c;var l=!f||!1!==f.wait;f=(f=navigator.userAgent.match(/AppleWebKit\/(\d+\.?\d*)/))&&
+f[1];if(null===h.onload&&!(536>f))h.onload=function(){h.onload=null;h.onerror=null;l&&e(h)},h.onerror=function(){console.error("Error loading stylesheet "+c);l&&e(h)};else if(l)var q=setInterval(function(){h.style&&(clearInterval(q),e(h))},15);(b||a.getElementsByTagName("head")[0]).appendChild(h);l||e(h)}var d="undefined"==typeof _css_cache?{}:_css_cache,a=document,b=a.head;f.insertCss=g;return f})},"dijit/main":function(){define(["dojo/_base/kernel"],function(g){return g.dijit})},"dojox/main":function(){define(["dojo/_base/kernel"],
function(g){return g.dojox})},"mw-browser-utils/BrowserCheck":function(){define("dojo/_base/window dojo/window dojo/dom-construct dojo/has dojo/i18n!./l10n/nls/unsupportedErrorPage ./detect/css ./detect/object".split(" "),function(g,f,d,a,b){var c={isBrowserValid:function(){var b=!0;a("quirks")?b=!1:a("css-enabled")?a("css-border-radius")?a("css-text-overflow")?a("object-create")||(b=!1):b=!1:b=!1:b=!1;return b},displayErrorAsOverlay:function(){d.create("div",{style:{position:"absolute",left:"0%",
top:"0%","background-color":"grey","-moz-opacity":"0.7",opacity:".70",filter:"alpha(opacity\x3d70)",width:"100%",height:"100%",zIndex:"90"},id:"fadeDiv"},g.body());d.create("div",{style:{position:"relative",margin:"auto","margin-top":"12.35%",width:"400px",height:"300px",padding:"10px",border:"2px solid black","background-color":"#ffffff","z-index":"100","font-family":"Sans-serif"},id:"unsupportedBrowser","class":"content_module"},g.body()).innerHTML=b.unsupportedError}};return{load:function(b,a,
d){c.isBrowserValid()?d():b?g.global.location=b:c.displayErrorAsOverlay()}}})},"dojo/window":function(){define("./_base/lang ./sniff ./_base/window ./dom ./dom-geometry ./dom-style ./dom-construct".split(" "),function(g,f,d,a,b,c,e){f.add("rtl-adjust-position-for-verticalScrollBar",function(a,c){a=d.body(c);c=e.create("div",{style:{overflow:"scroll",overflowX:"visible",direction:"rtl",visibility:"hidden",position:"absolute",left:"0",top:"0",width:"64px",height:"64px"}},a,"last");var f=e.create("div",
{style:{overflow:"hidden",direction:"ltr"}},c,"last"),h=0!=b.position(f).x;c.removeChild(f);a.removeChild(c);return h});f.add("position-fixed-support",function(a,c){a=d.body(c);c=e.create("span",{style:{visibility:"hidden",position:"fixed",left:"1px",top:"1px"}},a,"last");var f=e.create("span",{style:{position:"fixed",left:"0",top:"0"}},c,"last"),h=b.position(f).x!=b.position(c).x;c.removeChild(f);a.removeChild(c);return h});var q={getBox:function(a){a=a||d.doc;var c="BackCompat"==a.compatMode?d.body(a):
a.documentElement,e=b.docScroll(a);if(f("touch")){var g=q.get(a);a=g.innerWidth||c.clientWidth;c=g.innerHeight||c.clientHeight}else a=c.clientWidth,c=c.clientHeight;return{l:e.x,t:e.y,w:a,h:c}},get:function(a){if(f("ie")&&q!==document.parentWindow){a.parentWindow.execScript("document._parentWindow \x3d window;","Javascript");var b=a._parentWindow;a._parentWindow=null;return b}return a.parentWindow||a.defaultView},scrollIntoView:function(e,g){try{e=a.byId(e);var h=e.ownerDocument||d.doc,q=d.body(h),
p=h.documentElement||q.parentNode,k=f("ie")||f("trident"),u=f("webkit");if(e!=q&&e!=p)if(!(f("mozilla")||k||u||f("opera")||f("trident")||f("edge"))&&"scrollIntoView"in e)e.scrollIntoView(!1);else{var r="BackCompat"==h.compatMode,E=Math.min(q.clientWidth||p.clientWidth,p.clientWidth||q.clientWidth),y=Math.min(q.clientHeight||p.clientHeight,p.clientHeight||q.clientHeight);h=u||r?q:p;var v=g||b.position(e),n=e.parentNode;g=function(a){return 6>=k||7==k&&r?!1:f("position-fixed-support")&&"fixed"==c.get(a,
"position").toLowerCase()};var F=this;u=function(a,b,c){"BODY"==a.tagName||"HTML"==a.tagName?F.get(a.ownerDocument).scrollBy(b,c):(b&&(a.scrollLeft+=b),c&&(a.scrollTop+=c))};if(!g(e))for(;n;){n==q&&(n=h);var m=b.position(n),z=g(n),A="rtl"==c.getComputedStyle(n).direction.toLowerCase();if(n==h)m.w=E,m.h=y,h==p&&(k||f("trident"))&&A&&(m.x+=h.offsetWidth-m.w),m.x=0,m.y=0;else{var C=b.getPadBorderExtents(n);m.w-=C.w;m.h-=C.h;m.x+=C.l;m.y+=C.t;var w=n.clientWidth,D=m.w-w;0<w&&0<D&&(A&&f("rtl-adjust-position-for-verticalScrollBar")&&
(m.x+=D),m.w=w);w=n.clientHeight;D=m.h-w;0<w&&0<D&&(m.h=w)}z&&(0>m.y&&(m.h+=m.y,m.y=0),0>m.x&&(m.w+=m.x,m.x=0),m.y+m.h>y&&(m.h=y-m.y),m.x+m.w>E&&(m.w=E-m.x));var B=v.x-m.x,G=v.y-m.y,J=B+v.w-m.w,K=G+v.h-m.h;if(0<J*B&&(n.scrollLeft||n==h||n.scrollWidth>n.offsetHeight)){var x=Math[0>B?"max":"min"](B,J);A&&(8==k&&!r||5<=f("trident"))&&(x=-x);var H=n.scrollLeft;u(n,x,0);x=n.scrollLeft-H;v.x-=x}0<K*G&&(n.scrollTop||n==h||n.scrollHeight>n.offsetHeight)&&(x=Math.ceil(Math[0>G?"max":"min"](G,K)),H=n.scrollTop,
u(n,0,x),x=n.scrollTop-H,v.y-=x);n=n!=h&&!z&&n.parentNode}}}catch(M){console.error("scrollIntoView: "+M),e.scrollIntoView(!1)}}};g.setObject("dojo.window",q);return q})},"dojo/i18n":function(){define("./_base/kernel require ./has ./_base/array ./_base/config ./_base/lang ./_base/xhr ./json module".split(" "),function(g,f,d,a,b,c,e,q,r){d.add("dojo-preload-i18n-Api",1);var h=g.i18n={},l=/(^.*(^|\/)nls)(\/|$)([^\/]*)\/?([^\/]*)/,t=function(a,b,c,e){var k=[c+e];b=b.split("-");for(var d="",f=0;f<b.length;f++)if(d+=
(d?"-":"")+b[f],!a||a[d])k.push(c+d+"/"+e),k.specificity=d;return k},p={},k=function(a,b,c){c=c?c.toLowerCase():g.locale;a=a.replace(/\./g,"/");b=b.replace(/\./g,"/");return/root/i.test(c)?a+"/nls/"+b:a+"/nls/"+c+"/"+b},u=g.getL10nName=function(a,b,c){return a=r.id+"!"+k(a,b,c)},L=function(a,b,e,k,d,f){a([b],function(g){var h=c.clone(g.root||g.ROOT),u=t(!g._v1x&&g,d,e,k);a(u,function(){for(var a=1;a<u.length;a++)h=c.mixin(c.clone(h),arguments[a]);p[b+"/"+d]=h;h.$locale=u.specificity;f()})})},E=function(a){var e=
b.extraLocale||[];e=c.isArray(e)?e:[e];e.push(a);return e},y=function(b,e,k){if(d("dojo-preload-i18n-Api")){var f=b.split("*"),h="preload"==f[1];h&&(p[b]||(p[b]=1,m(f[2],q.parse(f[3]),1,e)),k(1));(f=h)||(n&&F.push([b,e,k]),f=n);if(f)return}b=l.exec(b);var u=b[1]+"/",r=b[5]||b[4],t=u+r;f=(b=b[5]&&b[4])||g.locale||"";var I=t+"/"+f;b=b?[f]:E(f);var D=b.length,B=function(){--D||k(c.delegate(p[I]))};a.forEach(b,function(a){var b=t+"/"+a;d("dojo-preload-i18n-Api")&&z(b);p[b]?B():L(e,t,u,r,a,B)})};d("dojo-preload-i18n-Api");
var v=h.normalizeLocale=function(a){a=a?a.toLowerCase():g.locale;return"root"==a?"ROOT":a},n=0,F=[],m=h._preloadLocalizations=function(b,e,k,d){function h(a,b){d.isXdUrl(f.toUrl(a+".js"))||k?d([a],b):w([a],b,d)}function u(a,b){for(a=a.split("-");a.length;){if(b(a.join("-")))return;a.pop()}b("ROOT")}function q(){for(--n;!n&&F.length;)y.apply(null,F.shift())}function l(k){k=v(k);u(k,function(g){if(0<=a.indexOf(e,g)){var l=b.replace(/\./g,"/")+"_"+g;n++;h(l,function(a){for(var b in a){var e=a[b],h=b.match(/(.+)\/([^\/]+)$/);
if(h){var l=h[2];h=h[1]+"/";if(e._localized){var r;if("ROOT"===g){var m=r=e._localized;delete e._localized;m.root=e;p[f.toAbsMid(b)]=m}else r=e._localized,p[f.toAbsMid(h+l+"/"+g)]=e;g!==k&&function(a,b,e,g){var h=[],l=[];u(k,function(c){g[c]&&(h.push(f.toAbsMid(a+c+"/"+b)),l.push(f.toAbsMid(a+b+"/"+c)))});h.length?(n++,d(h,function(){for(var d=h.length-1;0<=d;d--)e=c.mixin(c.clone(e),arguments[d]),p[l[d]]=e;p[f.toAbsMid(a+b+"/"+k)]=c.clone(e);q()})):p[f.toAbsMid(a+b+"/"+k)]=e}(h,l,e,r)}}}q()});return!0}return!1})}
d=d||f;l();a.forEach(g.config.extraLocale,l)},z=function(){},A={},C=new Function("__bundle","__checkForLegacyModules","__mid","__amdValue","var define \x3d function(mid, factory){define.called \x3d 1; __amdValue.result \x3d factory || mid;},\t   require \x3d function(){define.called \x3d 1;};try{define.called \x3d 0;eval(__bundle);if(define.called\x3d\x3d1)return __amdValue;if((__checkForLegacyModules \x3d __checkForLegacyModules(__mid)))return __checkForLegacyModules;}catch(e){}try{return eval('('+__bundle+')');}catch(e){return e;}"),
w=function(b,c,k){var d=[];a.forEach(b,function(a){function b(b){b=C(b,z,a,A);b===A?d.push(p[c]=A.result):(b instanceof Error&&(console.error("failed to evaluate i18n bundle; url\x3d"+c,b),b={}),d.push(p[c]=/nls\/[^\/]+\/[^\/]+$/.test(c)?b:{root:b,_v1x:1}))}var c=k.toUrl(a+".js");if(p[c])d.push(p[c]);else{var f=k.syncLoadNls(a);f||(f=z(a.replace(/nls\/([^\/]*)\/([^\/]*)$/,"nls/$2/$1")));if(f)d.push(f);else if(e)e.get({url:c,sync:!0,load:b,error:function(){d.push(p[c]={})}});else try{k.getText(c,!0,
b)}catch(I){d.push(p[c]={})}}});c&&c.apply(null,d)};z=function(a){for(var b,c=a.split("/"),e=g.global[c[0]],k=1;e&&k<c.length-1;e=e[c[k++]]);e&&((b=e[c[k]])||(b=e[c[k].replace(/-/g,"_")]),b&&(p[a]=b));return b};h.getLocalization=function(a,b,c){var e;a=k(a,b,c);y(a,f.isXdUrl(f.toUrl(a+".js"))?f:function(a,b){w(a,b,f)},function(a){e=a});return e};return c.mixin(h,{dynamic:!0,normalize:function(a,b){return/^\./.test(a)?b(a):a},load:y,cache:p,getL10nName:u})})},"mw-browser-utils/detect/css":function(){define(["dojo/has"],
function(g){function f(a,c){var b=!1,f=a.charAt(0).toUpperCase()+a.slice(1),g=d.length;c=c.style;if("string"===typeof c[a])b=!0;else for(;g;)if(--g,"string"===typeof c[d[g]+f]){b=!0;break}return b}var d=["Webkit","Moz","O","ms","Khtml"],a=g.add;a("css-enabled",function(a,c,e){a=c.documentElement;var b;if(!(b=c.body)){var d=!0;b=a.insertBefore(c.createElement("body"),a.firstChild)}a=b;b=e.style.display;e.style.display="none";a.insertBefore(e,a.firstChild);c=0===e.offsetWidth;a.removeChild(e);e.style.display=
b;d&&a.parentNode.removeChild(a);return c});a("css-content-box",function(a,c,e){var b;a=c.documentElement;var d=null;if(g("css-enabled")){if(!(b=c.body)){var f=!0;b=a.insertBefore(c.createElement("body"),a.firstChild)}e.style.cssText="position: absolute; top: -4000px; width: 40px; height: 40px; border: 1px solid black;";b.insertBefore(e,b.firstChild);d=40===e.clientWidth;b.removeChild(e);e.style.cssText=""}f&&b.parentNode.removeChild(b);return d});a("css-position-fixed",function(a,c,e){var b,d=c.documentElement,
f=null;if(g("css-enabled")){a=e.cloneNode(!1);if(!(b=c.body)){var l=!0;b=d.insertBefore(c.createElement("body"),d.firstChild)}c=b.style.cssText;b.style.cssText="padding:0;margin:0";e.style.cssText="position:fixed;top:42px";b.insertBefore(a,b.firstChild);b.insertBefore(e,a);f=e.offsetTop!==a.offsetTop;b.removeChild(e);b.removeChild(a);b.style.cssText=c;e.style.cssText=""}l&&b.parentNode.removeChild(b);return f});a("css-rgba",function(a,c,e){a=/^rgba/;c=null;if(g("css-enabled"))try{e.style.color="rgba(1,1,1,0.5)",
c=a.test(e.style.color),e.style.color=""}catch(q){}return c});a("css-border-radius",function(a,c,e){return f("borderRadius",e)});a("css-box-shadow",function(a,c,e){return f("boxShadow",e)});a("css-box-sizing",function(a,c,e){return f("boxSizing",e)});a("css-opacity",function(a,c,e){return f("opacity",e)});a("css-opacity-filter",function(a,c){return!g("css-opacity")&&"undefined"!==typeof c.documentElement.filters});a("css-resize",function(a,c,e){return f("resize",e)});a("css-selectable",function(a,
c,e){return f("userSelect",e)});a("css-style-float",function(a,c,e){return f("styleFloat",e)});a("css-pointerevents",function(a,c,e){return f("pointerEvents",e)});a("css-text-overflow",function(a,c,e){return f("textOverflow",e)});a("css-text-shadow",function(a,c,e){return f("textShadow",e)});a("css-transform",function(a,c,e){return f("transform",e)});return g})},"mw-browser-utils/detect/object":function(){define(["dojo/has"],function(g){var f=g.add,d={}.toString,a=Object;f("object-create",function(){return"[object Function]"===
d.call(a.create)});f("object-getprototypeof",function(){return"[object Function]"===d.call(a.getPrototypeOf)});f("object-seal",function(){return"[object Function]"===d.call(a.seal)});f("object-freeze",function(){return"[object Function]"===d.call(a.freeze)});f("object-issealed",function(){return"[object Function]"===d.call(a.isSealed)});f("object-isfrozen",function(){return"[object Function]"===d.call(a.isFrozen)});f("object-keys",function(){return"[object Function]"===d.call(a.keys)});f("object-preventextensions",
function(){return"[object Function]"===d.call(a.preventExtensions)});f("object-isextensible",function(){return"[object Function]"===d.call(a.isExtensible)});f("object-defineproperty",function(){return"[object Function]"===d.call(a.defineProperty)});f("object-defineproperties",function(){return"[object Function]"===d.call(a.defineProperties)});f("object-getownpropertydescriptor",function(){return"[object Function]"===d.call(a.getOwnPropertyDescriptor)});f("object-getownpropertynames",function(){return"[object Function]"===
d.call(a.getOwnPropertyNames)});f("object-es5",function(){return g("object-create")&&g("object-defineproperties")&&g("object-defineproperty")&&g("object-freeze")&&g("object-getownpropertydescriptor")&&g("object-getownpropertynames")&&g("object-getprototypeof")&&g("object-isextensible")&&g("object-isfrozen")&&g("object-issealed")&&g("object-keys")&&g("object-preventextensions")&&g("object-seal")});return g})},"mw-browser-utils/MobileBrowserCheck":function(){define(["dojo/_base/window","mw-html-utils/HtmlUtils",
"dojo/has"],function(g,f,d){var a={isBrowserValid:function(){var a=!0;null==f.parseQueryString().touch&&(d("ios")||d("android"))&&(a=!1);return a}};return{load:function(b,c,e){a.isBrowserValid()?e():g.global.location=b}}})},"mw-html-utils/HtmlUtils":function(){define(["dojo/io-query","mw-html-utils/_parseHtml/sanitize","mw-deprecation-utils/deprecation"],function(g,f,d){return{HYPERLINK_ESCAPE_REGEXP:/<a\s+href\s*=\s*"[^"]*"[^>]*>[\s\S]*?<\/a>/g,HYPERLINK_WITH_PARENTHESIS_ESCAPE_REGEXP:/<a\s+href\s*=\s*"([^"]*)"([^>]*)>([\s\S]*?)<\/a>/g,
STRONG_ESCAPE_REGEXP:/<strong>|<\/strong>/g,BOLD_LINK_ATTRIBUTE_REGEX:/\bstyle\s*=\s*"[^"]*\bfont-weight\s*:\s*bold\b[^"]*"/,parseQueryString:function(){var a=window.location.search.substr(1,window.location.search.length);return this._parseQueryString(a)},_parseQueryString:function(a){return g.queryToObject(a)},parseUrl:function(a){var b=document.createElement("a");b.display="none";b.href=a||window.location.href;b.href=b.href;b={protocol:b.protocol,hostname:b.hostname,port:b.port,pathname:b.pathname,
search:b.search,hash:b.hash};"https:"!==b.protocol&&"http:"!==b.protocol||0===b.pathname.indexOf("/")||(b.pathname="/"+b.pathname);"https:"===b.protocol&&"443"===b.port&&0!==a.indexOf("https://"+b.hostname+":443")&&(b.port="");return b},escapeHtml:function(a){var b=document.createElement("div");b.textContent=a;return b.innerHTML},escapeLinksAndHtml:function(a,b){d.deprecated({deprecated:{module:"mw-html-utils/HtmlUtils",method:"escapeLinksAndHtml"},replacement:{module:"mw-html-utils/HtmlUtils",method:"treatHtmlLikeCommandWindow"}});
var c="",e=a.split(this.HYPERLINK_ESCAPE_REGEXP),f=a.match(this.HYPERLINK_ESCAPE_REGEXP),g="",h=this,l=0,t=function(a,b,c,e){a=h.parseUrl(b).protocol;"http:"!==a&&"https:"!==a&&"matlab:"!==a&&(b="#");b=h.escapeHtml(b);e=h._strongNotEscaped(e,!0);g='\x3ca href\x3d"'+b+'"\x3e'+e+"\x3c/a\x3e"};if(b)c=this.escapeHtml(a),c=this.escapeWhitespace(c);else if(""!==e[0]&&(c=this._strongNotEscaped(e[0],!0)),null!==f&&0!==f.length)for(l=0;l<f.length;l+=1)f[l].replace(this.HYPERLINK_WITH_PARENTHESIS_ESCAPE_REGEXP,
t),""!==e[l+1]&&(e[l+1]=this._strongNotEscaped(e[l+1],!0)),c+=g+e[l+1];return c},treatHtmlLikeCommandWindow:function(a,b,c){if("string"!==typeof a)return"";var e="",d=a.split(this.HYPERLINK_ESCAPE_REGEXP),f=a.match(this.HYPERLINK_ESCAPE_REGEXP),g="",l=this,t=0;c=c||{};var p=function(a,b,c,e){a=l.parseUrl(b).protocol;var d="";"http:"!==a&&"https:"!==a&&"matlab:"!==a&&(b="#");b=l.escapeHtml(b);e=l._strongNotEscaped(e,!1);l.BOLD_LINK_ATTRIBUTE_REGEX.test(c)&&(d=' style\x3d"font-weight:bold"');g='\x3ca href\x3d"'+
b+'"'+d+"\x3e"+e+"\x3c/a\x3e"};if(b)e=this.escapeHtml(a);else if(""!==d[0]&&(e=this._strongNotEscaped(d[0],!1)),null!==f&&0!==f.length)for(t=0;t<f.length;t+=1)f[t].replace(this.HYPERLINK_WITH_PARENTHESIS_ESCAPE_REGEXP,p),""!==d[t+1]&&(d[t+1]=this._strongNotEscaped(d[t+1],!1)),e+=g+d[t+1];c.addPreTagToPreserveWhiteSpace&&(e='\x3cspan style\x3d"white-space: pre"\x3e'+e+"\x3c/span\x3e");return e},_strongNotEscaped:function(a,b){var c="",e=a.match(this.STRONG_ESCAPE_REGEXP),d=a.split(this.STRONG_ESCAPE_REGEXP),
f=function(a){return a};b&&(f=this.escapeWhitespace);b=0;if(null!==e&&0!==e.length)for(c=f(this.escapeHtml(d[0])),b=0;b<e.length;b+=1)c+=e[b]+f(this.escapeHtml(d[b+1]));else c=f(this.escapeHtml(a));return c},escapeWhitespace:function(a){d.deprecated({deprecated:{module:"mw-html-utils/HtmlUtils",method:"escapeWhitespace"},replacement:{module:"Plain HTML",method:'Set class as white-space: pre or use \x3cspan style\x3d"white-space: pre"\x3e...\x3c/span\x3e'}});return(a||"").replace(/\n/g,"\x3cbr\x3e").replace(/ {2}/g,
"\x26nbsp;\x26nbsp;")},handleAnchors:function(a,b){if(b.target.href){b.preventDefault();b.stopPropagation();var c=b.target.href;-1!==c.indexOf("matlab:")?"matlab:"===c.substring(0,7)&&(b=b.target.href.substring(7),a(window.unescape(b))):window.open(b.target.href)}},isElementOverflown:function(a){return a.scrollHeight>a.clientHeight||a.scrollWidth>a.clientWidth},sanitizeHtmlFromJava:f.sanitizeHtmlFromJava}})},"mw-html-utils/_parseHtml/sanitize":function(){define([],function(){var g="backgroundColor borderBottom borderBottomColor borderBottomLeftRadius borderBottomRightRadius borderBottomStyle borderBottomWidth borderLeft borderLeftColor borderLeftStyle borderLeftWidth borderRadius borderRight borderRightColor borderRightStyle borderRightWidth borderSpacing borderStyle borderTop borderTopColor borderTopLeftRadius borderTopRightRadius borderTopStyle borderTopWidth borderWidth color fontFamily fontSize fontStyle fontWeight height lineHeight margin marginBottom marginLeft marginRight marginTop maxHeight maxWidth minHeight minWidth overflow overflowWrap overflowX overflowY padding paddingBottom paddingLeft paddingRight paddingTop textAlign textAnchor textDecoration textIndent textOverflow textShadow textTransform width".split(" "),
f=function(d,a){var b=a.getAttribute("style");if(d.style&&null!==b&&""!==b)for(b=0;b<g.length;b+=1){var c=g[b],e=a.style[c];void 0!==d.style[c]&&(d.style[c]=e)}};return{sanitizeHtmlFromJava:function(d,a,b){return function(c){var e=function(b,c){for(var e=[],d=0;d<b.length;d+=1){var f=b[d];if(c.hasAttribute(f)){var g=c.getAttribute(f),h="";if(a[f]){h=a[f];g=String.prototype.trim.call(g);var l=g.indexOf(":");0>l&&h.relative[g.charAt(0)]?h=g:(l=g.substring(0,l),h=h[l+":"]?g:"#")}else h=g;e.push({key:f,
value:h})}}return e},g=function(a){var c=void 0;a.nodeType===window.Node.ELEMENT_NODE?d[a.tagName]?(c=document.createElement(a.tagName),e(d[a.tagName],a).forEach(function(a){c.setAttribute(a.key,a.value)}),b&&f(c,a)):c=document.createDocumentFragment():c=a.nodeType===window.Node.TEXT_NODE?document.createTextNode(a.textContent):document.createDocumentFragment();return c},r=function p(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:0,c=document.createDocumentFragment();if(150<b||!a)return c;
for(var e=a.firstChild;e;e=e.nextSibling){var d=g(e);e.nodeType===window.Node.ELEMENT_NODE&&d.appendChild(p(e,b+1));c.appendChild(d)}return c};c=(new DOMParser).parseFromString(c,"text/html");var h=void 0;return h=c.body?r(c.body):document.createDocumentFragment()}}({A:["target","href","title"],ABBR:["title"],ADDRESS:[],AREA:["shape","coords","href","alt"],ARTICLE:[],ASIDE:[],AUDIO:["autoplay","controls","loop","preload","src"],B:[],BDI:["dir"],BDO:["dir"],BIG:[],BLOCKQUOTE:["cite"],BR:[],CAPTION:[],
CENTER:[],CITE:[],CODE:[],COL:["align","valign","span","width"],COLGROUP:["align","valign","span","width"],DD:[],DEL:["datetime"],DETAILS:["open"],DIV:[],DL:[],DT:[],EM:[],FONT:["color","size","face"],FOOTER:[],H1:[],H2:[],H3:[],H4:[],H5:[],H6:[],HEADER:[],HR:[],I:[],IMG:["src","alt","title","width","height"],INS:["datetime"],LI:[],MARK:[],NAV:[],OL:[],P:[],PRE:[],S:[],SECTION:[],SMALL:[],SPAN:[],SUB:[],SUP:[],STRONG:[],TABLE:["width","border","align","valign"],TBODY:["align","valign"],TD:["width",
"rowspan","colspan","align","valign"],TFOOT:["align","valign"],TH:["width","rowspan","colspan","align","valign"],THEAD:["align","valign"],TR:["rowspan","align","valign"],TT:[],U:[],UL:[],VIDEO:"autoplay controls loop preload src height width".split(" ")},{href:{"http:":!0,"https:":!0,"mailto:":!0,"matlab:":!0,relative:{"#":!0,"/":!0}},src:{"http:":!0,"https:":!0,"mailto:":!0,relative:{"#":!0,"/":!0}}},!0)}})},"mw-deprecation-utils/deprecation":function(){define(["dojo/_base/config","mw-log/Log"],
function(g,f){var d={deprecated:function(a){if((g.isDebug||window.showDeprecationsAsErrors)&&this._isConfigValid(a)){var b=window.showDeprecationsAsErrors||a.deprecationLevel===this.ERROR?this.ERROR:this.WARN;var c="DEPRECATED: ";a.deprecated&&(c+=a.deprecated.module,a.deprecated.method&&(c+="."+a.deprecated.method+"()"),c+=".");a.replacement&&(c+=" Use "+a.replacement.module,a.replacement.method&&(c+="."+a.replacement.method+"()"),c+=" instead.");a.removalVersion&&(c+=" Will be removed in version: "+
a.removalVersion+".");a.geckNumber&&(c+=" Please use g"+a.geckNumber+" to track latest information regarding this deprecation");a.additionalInformation&&(c+=" "+a.additionalInformation);f[b](c)}},_isConfigValid:function(a){var b=!!a.deprecated&&"object"===typeof a.deprecated&&a.deprecated.hasOwnProperty("module");a.replacement&&(b=b&&"object"===typeof a.replacement&&a.replacement.hasOwnProperty("module"));a.geckNumber&&(b=b&&"number"===typeof a.geckNumber);b||f.error("Supplied deprecationConfig properties are not valid. Please refer to http://inside.mathworks.com/wiki/Web_Widgets_Deprecation_API for right API");
return b}};Object.defineProperties(d,{WARN:{value:"warn",enumerable:!0},ERROR:{value:"error",enumerable:!0}});return d})},"mw-log/Log":function(){var g=function(){function f(d,a){for(var b=0;b<a.length;b++){var c=a[b];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(d,c.key,c)}}return function(d,a,b){a&&f(d.prototype,a);b&&f(d,b);return d}}();define(["mw-log/impl/Modes","mw-log/impl/Levels","mw-log/impl/Backlog","mw-log/util/LogUtils"],function(f,
d,a,b){var c=a.create(100),e={},q=0,r=d.DEBUG,h=f.DEVELOPMENT,l=[],t={};return new (function(){function a(c){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");null!=t[c]?t.DEFAULT.error("a logger with the name '"+c+"' already exists - change the name to prevent interference"):(b.makeReadOnlyProperty(this,"name",c),t[this.name]=this,this._timers={},this._threshold=d.DEBUG,this._showTimestamp=!0,b.makeReadOnlyProperty(this,"modes",f),b.makeReadOnlyProperty(this,"levels",
d))}g(a,[{key:"_shouldLog",value:function(a){return r>a&&this._threshold>a}},{key:"_nameAndTime",value:function(){var a=[];"DEFAULT"!==this.name&&a.push(this.name);this._showTimestamp&&a.push(b.currentTimeString());return a}},{key:"table",value:function(a){if(this._shouldLog(3)){var d={namespace:this.name,type:"table",message:[a],time:new Date};c.add(d);b.printToConsole("log",this._nameAndTime(),h);b.printToConsole("table",[a],h);b.execCallbacks(e,d)}}},{key:"trace",value:function(){if(this._shouldLog(3)){var a=
{namespace:this.name,type:"trace",message:null,time:new Date},d=Error().stack.split("\n");for("Error"===d[0]&&d.shift();d[0].includes("Log.js")||d[0].includes("logger.trace")||"trace"===d[0];)d.shift();d=d.join("\n");a.message=[d];c.add(a);b.printToConsole("log",this._nameAndTime(),h);b.printToConsole("trace",[],h);b.execCallbacks(e,a)}}},{key:"time",value:function(a){this._shouldLog(3)&&(null==this._timers[a]?this._timers[a]=(new Date).getTime():this.warn('timer "'+a+'" already exists.'))}},{key:"timeEnd",
value:function(a){if(this._shouldLog(3)){var d={namespace:this.name,type:"timeEnd",message:null,time:new Date};if(null!=this._timers[a]){var f=(new Date).getTime()-this._timers[a];d.message=[a+": "+f+"ms - timer ended"];c.add(d);b.printToConsole("log",this._nameAndTime().concat(d.message),h);b.execCallbacks(e,d);this._timers[a]=null}else this.warn('timer "'+a+"\" doesn't exist.")}}},{key:"_group",value:function(a,d){if(this._shouldLog(3)){d=d?"groupCollapsed":"group";var f={namespace:this.name,type:d,
message:[a],time:new Date};l.push(a);c.add(f);b.printToConsole(d,[a],h);b.execCallbacks(e,f)}}},{key:"groupCollapsed",value:function(a){this._group(a,!0)}},{key:"group",value:function(a){this._group(a,!1)}},{key:"groupEnd",value:function(){if(this._shouldLog(3)){var a=l.pop();a={namespace:this.name,type:"groupEnd",message:[a],time:new Date};c.add(a);b.printToConsole("groupEnd",[],h);b.execCallbacks(e,a)}}},{key:"assert",value:function(a,d){this._shouldLog(0)&&!a&&(a={namespace:this.name,type:"assert",
message:["Assertion failed:",d],time:new Date},c.add(a),b.printToConsole("assert",this._nameAndTime().concat(a.message),h),b.execCallbacks(e,a))}},{key:"_basicLogMethod",value:function(a,d,f){this._shouldLog(d)&&(d={namespace:this.name,type:a,message:f,time:new Date},f=this._nameAndTime().concat(f),c.add(d),b.printToConsole(a,f,h),b.execCallbacks(e,d))}},{key:"debug",value:function(a){var b=Array.prototype.slice.call(arguments);this._basicLogMethod("debug",4,b)}},{key:"log",value:function(a){var b=
Array.prototype.slice.call(arguments);this._basicLogMethod("log",3,b)}},{key:"dir",value:function(a){var b=Array.prototype.slice.call(arguments);this._basicLogMethod("dir",3,b)}},{key:"info",value:function(a){var b=Array.prototype.slice.call(arguments);this._basicLogMethod("info",2,b)}},{key:"warn",value:function(a){var b=Array.prototype.slice.call(arguments);this._basicLogMethod("warn",1,b)}},{key:"error",value:function(a){var b=Array.prototype.slice.call(arguments);this._basicLogMethod("error",
0,b)}},{key:"addCallback",value:function(a,b){e[q]=a;b&&c.applyCallback(a);a={};var d=q;a.remove=function(){delete e[d]};q++;return a}},{key:"createLogger",value:function(b){var c=new a(b);return c.name?c:t[b]}},{key:"threshold",get:function(){return this._threshold},set:function(b){this._threshold=a._sanitizeLevel(b)}},{key:"showTimestamp",get:function(){return this._showTimestamp},set:function(a){this._showTimestamp=!!a}},{key:"globalThreshold",get:function(){return r},set:function(b){r=a._sanitizeLevel(b)}},
{key:"mode",get:function(){return h},set:function(b){h=a._sanitizeMode(b)}}],[{key:"_sanitizeLevel",value:function(a){return"number"===typeof a?a:d.DEBUG}},{key:"_sanitizeMode",value:function(a){return-1<b.objectValues(f).indexOf(a)?a:f.development}}]);return a}())("DEFAULT")})},"mw-log/impl/Modes":function(){define([],function(){var g={DEVELOPMENT:"DEVELOPMENT",PRODUCTION:"PRODUCTION"};Object.freeze(g);return g})},"mw-log/impl/Levels":function(){define([],function(){var g={DEBUG:5,LOG:4,TABLE:4,
TIME:4,DIR:4,INFO:3,WARN:2,ASSERT:1,ERROR:1};Object.freeze(g);return g})},"mw-log/impl/Backlog":function(){define(["mw-log/util/LogUtils"],function(g){return{create:function(f){var d={},a=[];g.makeReadOnlyProperty(d,"size",f);var b=0;d.add=function(c){a[b]=c;b=(b+1)%d.size};d.applyCallback=function(c){var e=b+1;void 0===a[e]&&(e=0);for(var g=0;g<d.size&&void 0!==a[e];)c(a[e]),e=(e+1)%f,g++};return d}}})},"mw-log/util/LogUtils":function(){define(["mw-log/impl/Modes"],function(g){var f={objectValues:function(d){var a=
[],b;for(b in d)a.push(d[b]);return a},makeReadOnlyProperty:function(d,a,b){Object.defineProperty(d,a,{value:b,writable:!1})},execCallbacks:function(d,a){d=f.objectValues(d);for(var b in d)d[b](a)},currentTimeString:function(){var d=new Date;return d.toLocaleTimeString("en-US",{hour12:!1,hour:"numeric",minute:"numeric",second:"numeric"})+"."+d.getTime()%1E3},printToConsole:function(d,a,b){b===g.PRODUCTION&&"error"!==d||console[d].apply(console,a)}};return f})},"mw-browser-utils/DeprecatedBrowserCheck":function(){define(["dojo/_base/window",
"dojo/window"],function(g,f){var d={isBrowserValid:function(){var a=navigator.userAgent,b=a.match(/(msie|trident|edge(?=\/))\/?\s*(\d+)/i)||[];return b[1]&&("MSIE"===b[1]||"msie"===b[1]||/trident/i.test(b[1]))&&(a=/\brv[ :]+(\d+)/g.exec(a)||[],12>parseInt(a[1]))?!1:!0}};return{load:function(a,b,c){!d.isBrowserValid()&&a?g.global.location=a:c()}}})},"*now":function(g){g(['dojo/i18n!*preload*MOTW/nls/browsercheck*["ja-jp","ko-kr","zh-cn","en-us","ROOT"]'])}}});define("MOTW/browsercheck",[],1);